version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: db_transcendence
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_NAME: ${POSTGRES_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - sonarnet

  redis:
    image: redis:6
    container_name: redis_channels
    ports:
      - "6379:6379"

volumes:
  postgres:
    name: postgres_db

networks:
  sonarnet:
    driver: bridge
