version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: db_transcendence
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./transcendence/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres_db