version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: db_transcendence
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./transcendence/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - sonarnet

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./transcendence/.env
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - sonarnet

  sonarqube:
    image: sonarqube:community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: cavalinho
      SONAR_JDBC_PASSWORD: root
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonarnet

volumes:
  postgres:
    name: postgres_db
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  sonarnet:
    driver: bridge
