version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: db_transcendence
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cavalinho
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_DB: db_transcendence
      POSTGRES_NAME: db_transcendence
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - sonarnet

volumes:
  postgres:
    name: postgres_db

networks:
  sonarnet:
    driver: bridge
