name: Django CI

on:
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
      AUTH_URL_INTRA: ${{ secrets.AUTH_URL_INTRA }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v3



      - name: Run Script in Docker Container
      run: |
        run: docker-compose up -d --build
        docker exec -i ${SERVER_CONTAINER_NAME} sh -c "python manage.py makemigrations && python manage.py migrate"
        docker exec -i ${SERVER_CONTAINER_NAME} sh -c "./test.sh"
