name: Django CI

on:
  push:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.4]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r transcendence/requirements/local.txt

    - name: Create .env file
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
        echo "POSTGRES_NAME=${{ secrets.POSTGRES_NAME }}" >> .env


    - name: Run docker-compose
      run: |
        export $(cat .env | xargs)
        docker-compose up -d --build

    - name: Apply Migrations
      run: |
        sleep 30
        cd transcendence
        python manage.py migrate
      env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "True"
          DB_NAME: ${{ secrets.POSTGRES_DB }}
          DB_USER: ${{ secrets.POSTGRES_USER }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      
    - name: Run Tests
      run: |
        cd transcendence
        chmod 777 test.sh
        ./test.sh
        
        
