name: Django CI

on:
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v3

    # - name: test
    #   run: make test
        - name: Run docker-compose
      run: docker-compose up -d --build

    - name: Apply Migrations
      run: |
        sleep 24
        cd transcendence
        python manage.py makemigrations
        python manage.py migrate
      
    - name: Run Tests
      run: |
        cd transcendence
        chmod 777 test.sh
        ./test.sh
